### ISSUE TITLE
Some functions not displaying complete parameters and return values

### ISSUE THREAD

**Issue by brucify** [erldocs/erldocs#28]
Reposted from https://github.com/erldocs/erldocs.com/issues/4

Some functions are not displaying correctly. For example
http://erldocs.com/current/stdlib/lists.html?i=4&search=keysear#keysearch/3
Instead of 
```erlang
keysearch/3
1..tuple_size(Tuple)
```
the correct display should be
```erlang
keysearch(Key, N, TupleList) -> {value, Tuple}
```

**Example 1**: `lists:keysearch` 
On erldocs.com (**incorrect**): http://erldocs.com/18.1/stdlib/lists.html?i=4&search=keysear#keysearch/3
On erlang.org (**correct**): http://www.erlang.org/doc/man/lists.html#keysearch-3 
```erlang
keysearch/3
1..tuple_size(Tuple)
```

It is because their XML file has a special format, and does not contain the parameter information: https://github.com/erlang/otp/blob/maint/lib/stdlib/doc/src/lists.xml#L348
```xml
<func>
      <name name="keysearch" arity="3"/> 
...
```
To solve this issue, the correct information must be fetched from the .erl source at 
https://github.com/erlang/otp/blob/OTP-18.0/lib/stdlib/src/lists.erl#L68-L72
```erlang
-spec keysearch(Key, N, TupleList) -> {value, Tuple} | false when
      Key :: term(),
      N :: pos_integer(),
      TupleList :: [Tuple],
      Tuple :: tuple().
```

However, some functions are working correctly because their xml is written in a different way.

**Example 2**: `inets:start`
On erldocs.com (**correct**): http://erldocs.com/18.1/inets/inets.html?i=2&search=inets:start#start/2
On erlang.org (**correct**): http://www.erlang.org/doc/man/inets.html#start-2
```erlang
start(Service, ServiceConfig) -> {ok, Pid} | {error, Reason}
```

Because their XML file contains this information: https://github.com/erlang/otp/blob/maint/lib/inets/doc/src/inets.xml#L123
```xml
<func>
      <name>start(Service, ServiceConfig) -> {ok, Pid} | {error, Reason}</name>
...
```

**Comment by jfacorro** [comment]
@brucify Building the docs for OTP releases 17.5 and 18.1 with the current `master` branch of `erldocs` shows the correct specs for the functions in the `lists` module (see screenshot).

![screen shot 2015-11-24 at 3 51 13 pm](https://cloud.githubusercontent.com/assets/1522569/11377174/41ac4684-92c3-11e5-9201-d31eb840d789.png)

The problem with the documentation for the `erlang` module is that the `.erl` files are under the `/erts/preloaded/src/` directory. This structure does not conform to the default application directory structure, so `erldocs` is currently not able to find the `.erl` source files, therefore it can't extract the specs from them and properly generate the documentation for the module. 

After forcing `erldocs` to check the `erts/preloaded/src` directory as well, the documentation generated for the `erlang` module includes all the corresponding specs.

```erlang
ensure_docsrc (Conf, AppDir) ->
    %% List any doc/src/*.xml files that exist in the source files
    XMLFiles = filelib:wildcard(filename:join([AppDir, "doc", "src", "*.xml"])),
    HandWritten = [bname(File, ".xml") || File <- XMLFiles],

    ErlFiles = filelib:wildcard(filename:join([AppDir,        "*.erl"]))
        ++     filelib:wildcard(filename:join([AppDir, "src", "*.erl"]))
        ++     filelib:wildcard(filename:join([AppDir, "preloaded", "src", "*.erl"])), %% Line added

    %% ...
```

![screen shot 2015-11-24 at 3 56 59 pm](https://cloud.githubusercontent.com/assets/1522569/11377326/0f53fac8-92c4-11e5-8a2e-b0b9c42d778d.png)

This issue has its origin in the particular way the code from `otp` is organized and not how `erldocs` works. 

@fenollp Maybe I could add an additional configuration parameter to `erldocs` so that the user could specify additional subdirectories where there could be `.erl` source files. Something like: `--src "preloaded/src`. What do you think?

**Comment by fenollp** [comment]
@jfacorro nice catch!
On the option idea: I would prefer this kind of behaviour not to be openly supported.
I'm thinking activating this line should be done once we have a `building_otp` flag (after #30).
Also, this would probably fix #26.

Maybe we should add something that greps through OTP HTML files for functions that were rendered as `keysearch/3` instead of their spec-ed version, as a test.

Are you confident `preloaded/` is the only place we should add?

**Comment by jfacorro** [comment]
@fenollp [Here](https://gist.github.com/jfacorro/539b86d600e9d6173a17) is a comprehensive report of all the modules (from OTP 17.5) for which there is a valid hand written documentation xml file but its corresponding Erlang file is not found.

The following `detect_missing_src_files/4` function is called form `ensure_docsrc/2` in `erldocs_core.erl` while generating the docs for OTP 17.5:

```erlang
is_buildable_xml_file(Conf, Path) ->
    {Type, _, _} = read_xml(Conf, Path),
    lists:member(Type, buildable()).

detect_missing_src_files(Conf, AppDir, XMLFiles, ErlFiles) ->
    BuildableXmlFiles = [File || File <- XMLFiles, is_buildable_xml_file(Conf, File)],

    HandWritten = [bname(File, ".xml") || File <- BuildableXmlFiles],
    ErlModules  = [bname(File, ".erl") || File <- ErlFiles],

    Missing = [HW || HW <- HandWritten, not lists:member(HW, ErlModules)],

    case Missing of
        [] -> ok;
        _ ->
            file:write_file( "missing.txt"
                           , ["====== ",  AppDir, " ======", "\n"]
                           , [append]
                           ),
            [file:write_file("missing.txt", [X, "\n"], [append]) || X <- Missing]
    end.
```

**Comment by fenollp** [comment]
Ok. What is this list good for?

**Comment by jfacorro** [comment]
@fenollp I can think of two options: 

1. Manually check what is the situation in each application so that for those where the hand written documentation is incomplete the path to the source files is added as a special case when `building_otp`.
2. Include an additional step where the `ensure_docsrc/2` function looks for each of the missing source files in the application's folder recursively. This can be done using the `filelib:wildcard/1` function and the `**` in the path. For example if we are processing the `erts` application and we find there's an `erlang.xml` but no `erlang.erl`, search for it by calling `filelib:wildcard(filename:join([AppDir, "**", "erlang.erl"]))`. The advantage of this approach is it generalizes for all cases, the disadvantage is searching all of the files under the application's folder `n` times can be pretty time consuming.

**Comment by fenollp** [comment]
I like option 2, only:
* It has to be only when `building_otp`
* Use `filelib:fold_files` which should help a lot, instead of a wildcard of `**`. (not sure the double star is supported on all machines)

**Comment by jfacorro** [comment]
@fenollp So before I go ahead and implement option 2, should I wait for #30 to be merged? I don't see that PR including any flags so I guess I would have to include that as part of the resolution of this issue.

**Comment by fenollp** [comment]
@jfacorro Yes add your own flag. Just add to `Conf` something along the lines of `{building_otp, filelib:is_file("/otp_build")}`

**Comment by brucify** [comment]
@fenollp 

Some functions are not displaying on `current` for some reason.

On `maint`, but NOT on `current`:
http://erldocs.com/current/kernel/file.html?i=15&search=write#pwrite/3
http://erldocs.com/maint/kernel/file.html?i=15&search=write#pwrite/3

On both `maint` and `current` (working):
http://erldocs.com/current/stdlib/lists.html?i=0&search=keysear#keysearch/3
http://erldocs.com/maint/stdlib/lists.html?i=0&search=keysear#keysearch/3

On the other hand, is it possible to deploy these for older versions as well? For example http://erldocs.com/17.5/

Thanks!

**Comment by fenollp** [comment]
@brucify There was #44 which only appeared on my Debian (prod). Fixed now, pushed an update of all `erldocs.com/*/` just now, changes should be appearing slowly as GitHub's CDN clears up.

**Comment by brucify** [comment]
It's working again. Thanks @fenollp !
