### ISSUE TITLE
generate erldocs for riak project

### ISSUE THREAD

**Issue by bryanhuntesl** [erldocs/erldocs#64]
Hi, 

This is  a question, rather than erldocs issue - I'm looking for implementation advice. 

I'd like to have provide something like erldocs for the Riak codebase.

It's worth mentioning that the Riak build system is very legacy (erlang 16, rebar(2), makefiles, shell scripts, etc). 

Would you recommend erldocs as a starting point for such a project or if not, could you recommend anything else?

I know that `rebar3` (`rebar3 edoc`) makes this easy (presumably) but we're stuck with `rebar` for the foreseeable future.

Oh and if this is the wrong place to ask, happy to close this issue and re-post elsewhere. 

Thanks,

Bryan

**Comment by fenollp** [comment]
This is indeed the maintained version of erldocs :)

So erldocs is not yet a rebar3 plugin (see #54 for this), it is however an escript.
You can do:
```shell
git clone git@github.com:basho/riak_core.git # well, generate HRLs if some need to be
git clone git@github.com:erldocs/erldocs.git
( cd erldocs && rebar3 compile )
./erldocs/_build/default/bin/erldocs -o site/ riak_core/
...bla bla bla...
( cd site/ && python3 -m http.server )
```
which should not need any specific version of OTP (it just worked for me on 20.3).

http://other.erldocs.com used to have content + get updated daily but bugs in erldocs as well as erldocs_other (mainly the code skipping updates + string encoding) need fixing before starting that cron again. I have also found a better static hosting provider which I have played with to handle such a huge website. I really want http://other.erldocs.com to be real again especially since I see it mentioned in different places!

I encourage you to try erldocs and submit issues / PRs if you need to. I'd love to discuss my plans for erldocs (maybe generate markdown instead of HTML, ...) as I know its style does not please everyone.
Know however that any contributions to erldocs will eventually end up enhancing other.erldocs.com thus providing better docs for the whole (reachable) open source Erlang community!

**Comment by fenollp** [comment]
Hey there @bryanhuntesl. Any luck?

**Comment by bryanhuntesl** [comment]
Sorry @fenollp - should have replied earlier. Yes, it works great. Question - I'd like to get the aggregate the documentation for everything into a single html file. How would you recommend doing this, symbolic links ?

**Comment by fenollp** [comment]
Can’t help with that.

**Comment by bryanhuntesl** [comment]
For the reference of anyone needing to do this at some point in the future, it was trivial, and the output is now on https://bryanhuntesl.github.io/riak-docs/ . 

The command (executed on a checkout out Riak (and `rebar get-deps`) was : 

```
erldocs $( find ./deps ./apps/riak/src -name "src" \
| egrep -v "(erlang_js|demo|template|erlydtl|build|proper|sample|build|priv|templates|demo|erlang_js|exometer_core/test)" \
| sed -e 's/\/src//' | tr "\n" ' ' )
```

Works beautifully, thanks @fenollp
