### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [erldocs/erldocs#75]
## Remove Google Analytics

This commit removes the Google Analytics 'functionality' from this page. Following on
from the previous commit, this change also greatly improves the privacy of 
unsuspecting users.

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by fenollp** [comment]
Sorry I haven't taken the time to respond. I agree this is a valid issue and dislike the existing solution.

I am collecting analytics solely to give the community a kind of stethoscope, and have never managed to get GA to distribute this data in free access. 

Since erldocs.com (and soonTM other.erldocs.com) are hosted for free at Netlify I am investigating https://www.netlify.com/products/analytics/ which so far has the benefit of not running in the browser wasting cycles.

I'll reopen this so I can keep you updated.

**Comment by fenollp** [comment]
Oh well it's $9/month/site
